<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KAVI-VASANTH" failures="1" tests="4" name="Test" time="0.178" errors="0" timestamp="2022-11-18T21:48:14 IST">
  <testcase classname="com.testng.Failed_Test_Rerun" name="password" time="0.031">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.testng.Failed_Test_Rerun" name="password" time="0.005">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.testng.Failed_Test_Rerun" name="password" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [@143] but found [@341]">
      <![CDATA[java.lang.AssertionError: expected [@143] but found [@341]
at com.testng.Failed_Test_Rerun.password(Failed_Test_Rerun.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- password -->
  <testcase classname="com.testng.Failed_Test_Rerun" name="username" time="0.004"/>
</testsuite> <!-- Test -->
